Draft #23 Adapts Gpios power management to Access
Coppernic/CoreSample pull request #24
Opened 2022-02-21 15:44 UTC by FlorentYvinec

2022-02-21 15:51 UTC, bastienpaulfr approved these changes

2022-02-21 15:58 UTC, mreynier commented on app/src/main/java/fr/coppernic/samples/core/ui/HdkAccessFragment.java
> +public class HdkAccessFragment extends Fragment {
Could you translate in Kotlin and remove butterknife for this fragment..?

2022-02-21 15:59 UTC, mreynier requested changes
could you remove butterknife?

2022-02-21 16:29 UTC, mcghorayeb commented on app/src/main/res/layout/fragment_hdk_access.xml
> +        android:id="@+id/toggle2VccEn"
c'est quoi le "2" dans l'id (toggle2)

2022-02-22 10:07 UTC, FlorentYvinec commented on app/src/main/res/layout/fragment_hdk_access.xml
> +        android:id="@+id/toggle2VccEn"
Oui ca a pas trop de sens, j'enlève

2022-02-22 11:05 UTC, merged